# Please don't modify this file
# Please don't modify this file
# Please don't modify this file
# modify only config.env file. you can override the variables here in config.env 

global:

  # fake site when someone without proxy wants to use this proxy
  decoy_site: https://www.google.com/

  # can be a string with any lenght (automatically generate if is "change")
  base_proxy_path: "change"

  # allow only tls ports and http ports in firewall
  firewall: true

  # resource monitoring
  netdata: true

  # allow unencrypted proxy
  http_proxy: true

  # iran_sites can be block, proxy, cfwrap, cfwrap means cloud flare wrap
  iran_sites: proxy

  # if the request is other domains
  allow_invalid_sni: true

  auto_update: true

  speed_test: true

  # disable ipv6
  only_ipv4: true
  
  custom_cdn_server: ""
  custom_cdn_sni: ""


# admin secret will be changed to random if it contains "0000000000000000000000000000000"
admin_secret: "00000000000000000000000000000001" 

# list of users in the system
users:
  - name: "hiddify"

    # uuid is 32 char (user will be ignored if uuid contains 0000000000000000000000000000000)
    uuid: "00000000000000000000000000000000"

    # bandwidth is a float in GB. 0 means unlimited
    monthly_usage_limit: 10

    # used bandwidth this month
    current_usage: 0

    # expire time (monthly bandwith will be reset every 30 days before expiry time)
    expiry_time: "2023/02/10"

domains:
   # should be unique
   - test.hiddify.com        


telegram:
  enable: true

  # 32 char uuid common between all your users
  # will be changed to random if uuid contains 0000000000000000000000000000000
  secret: "00000000000000000000000000000000"

  # demonestrate fake_tls_domain for preventing probing, should be unique
  fake_tls_domain: mail.google.com

  #adtag not supported now
  # ad_tag:  

ss_faketls:
  enable: true

  # 32 char uuid common between all your users
  # will be changed to random if uuid contains 0000000000000000000000000000000
  secret: "00000000000000000000000000000000"

  # demonestrate fake_tls_domain for preventing probing, should be unique
  fake_tls_domain: www.google.com
    
xray:
  enable: true
  # list of ports for tls entry point
  tls_ports: 
    - 443

  # list of ports for http entry point (port 80 is mandatory)
  http_ports: 
    - 80

  configs:
     transport:
       kcp: false
       http: false
       grpc: true
       ws: true
       
     protocols:
       vmess: true
       trojan: true
       vless: true





github:
   user: hiddify
   repository: hiddify-config
   branch_or_tag: main

